default: &default
  adapter: postgresql
  encoding: unicode
  host: db       
  username: postgres
  password: postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_dev

test:
  <<: *default
  database: todo_test
